### ISSUE TITLE
Was macht das? Wieso ist das da?

### ISSUE THREAD

**Issue by cineafx** [OstfaliaSS18Team8/Lupus#57]
https://github.com/OstfaliaSS18Team8/Lupus/blob/d2deb4e273ceef118e37d6948130f8340774d751/Lupus.inform/Source/story.ni#L970

**Comment by AndreZuechner** [comment]
Keine Ahnung wo das herkommt. Würde mal tippen das dass Reste vom Testen sind. Nehme ich im nächsten commit raus.
